# Generated by Django 2.2.28 on 2022-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='media',
            field=models.ImageField(default='no_image.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
